# active spring boot profile
spring:
   profiles:
      active: development

---
# common spring boot configuration
spring:

   mvc:
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
   web:
      resources:
       # Locations of static resources
         static-locations: classpath:/assets/, file:/goodmorning-uploads/  

   redis:
      host: localhost
      port: 6379
      
   #mail
   mail:
      host: smtp.gmail.com
      port: 587
      username: choisichang13@gmail.com
      password: pqtrwciijdhpqqik
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
                  
# template engine
#   freemarker:
#      template-loader-path: classpath:/templates
#      suffix: .ftl
   thymeleaf:
      prefix : classpath:templates/
      check-template-location: true
      mode: HTML5
      suffix : .html
      cache : false
    
# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

# logging
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
   file:
      name: logs/${spring.application.name}.log
      max-history: 30
   level:
      root: INFO
      me:
         kickscar:
            mysite:
               exception: ERROR         
---
# development profile: spring boot configuration
spring:
   config:
      activate:
         on-profile: development

   # devtools - live reload
   devtools:
      livereload:
         enabled: true

# DataBase
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.10.46:3306/employees?charset=utf8
      username: hr
      password: hr
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
         
# server
server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
---
# production profile: spring boot configuration
spring:
   config:
      activate:
         on-profile: production

# DataBase
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://34.64.83.208:3306/goodmorning?charset=utf8
      username: ENC(zPCspAbRWtf/yA50+PyeFYCDx1ZUkoPX3WIp/V7+5gXJNFHXb5AEWSxg2XFBBJZw)
      password: ENC(YUeIVcQ32Lbtasm1eZeujUbFBYS7cJX9f9kWTiUahNFYGDioSKAy44GpC62azMZ+Rm31kZhgtXIOXkdOV8BalA==)
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

jasypt:
   encryptor:
      bean: jasyptStringEncryptor
         
# server
server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true