# active spring boot profile
spring:
   profiles:
      active: development

---
# common spring boot configuration
spring:

   mvc:
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
   web:
      resources:
       # Locations of static resources
         static-locations: classpath:/templates/
   redis:
      host: localhost
      port: 6379

# template engine
   freemarker:
      template-loader-path: classpath:/templates
      suffix: .ftl

# DataBase
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.10.46:3306/employees?charset=utf8
      username: hr
      password: hr
#      hikari:
#         minimum-idle: 10
#         maximum-pool-size: 20
    
# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

# logging
#logging:
#   level:
#      root: INFO  
---
# development profile: spring boot configuration
spring:
   config:
      activate:
         on-profile: development

   # devtools - live reload
   devtools:
      livereload:
         enabled: true
         
# server
server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
---
# production profile: spring boot configuration
spring:
   config:
      activate:
         on-profile: production
         
# server
server:
   port: 8088
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true